<?xml version="1.0" encoding="utf-8"?>
<pysystest type="auto">

    <description>
        <title>Error: group txs in a batch with one causing a revert</title>
        <purpose><![CDATA[
The idea of the test is to have four transactions waiting to be processed pre-loaded into the mempool, where one of
them will be reverted. This is done by feeding in the txs with decreasing nonces, so that when the lowest nonce is
finally sent, all the txs should then get processed. We want to make sure all txs are mined correctly with no issue
in the network.
]]>
        </purpose>
    </description>

    <classification>
        <groups inherit="true">
            <group>error</group>
        </groups>
        <modes inherit="true">
            <mode>ten.sepolia</mode>
            <mode>ten.uat</mode>
            <mode>ten.dev</mode>
            <mode>ten.local</mode>
            <mode>ganache</mode>
            <mode>sepolia</mode>
            <mode>arbitrum.sepolia</mode>
        </modes>
    </classification>

    <data>
        <class name="PySysTest" module="run"/>
    </data>

    <traceability>
        <requirements>
            <requirement id=""/>
        </requirements>
    </traceability>
</pysystest>
